# Generated by Django 2.2.3 on 2019-07-15 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhisingWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('name_parse', models.CharField(max_length=200)),
                ('cat_parse', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='media/photo/')),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_host', models.GenericIPAddressField()),
                ('long_t', models.CharField(blank=True, max_length=200, null=True)),
                ('lat_t', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('web_load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phiser.PhisingWeb')),
            ],
        ),
    ]
